/**
 * Memory Content Validation Functions
 *
 * These functions validate that content being saved as memories is user content,
 * not AI assistant responses. This prevents accidental saving of AI responses.
 */

/**
 * Validates that content is appropriate for saving as a memory
 * @param content The content to validate
 * @param validationLevel How strict the validation should be
 * @returns true if content is valid for memory saving
 */
export const validateMemoryContent = (
  content: string,
  validationLevel: "strict" | "normal" | "lenient" = "normal"
): boolean => {
  if (!content || typeof content !== "string") {
    console.warn("❌ Invalid content type for memory:", typeof content)
    return false
  }

  const trimmedContent = content.trim()
  if (trimmedContent.length === 0) {
    console.warn("❌ Empty content rejected for memory")
    return false
  }

  // Check for AI response indicators
  const aiIndicators = [
    /^I can help you/i,
    /^Here's how/i,
    /^Let me explain/i,
    /^Based on/i,
    /^I understand/i,
    /^That's a great question/i,
    /^I'll help you/i,
    /^Here's what/i,
    /^To answer your question/i,
    /^I'd be happy to/i,
    /^As an AI assistant/i,
    /^I'm here to help/i,
    /^Let me assist you/i,
    /^I can assist you/i,
    /^Here's the answer/i,
    /^The answer is/i,
    /^To solve this/i,
    /^Here's a solution/i,
    /^The solution is/i,
    /^You can solve this by/i,
    /^To fix this issue/i,
    /^The problem is/i,
    /^The issue is/i,
    /^Let me show you/i,
    /^I'll show you/i,
    /^Here's an example/i,
    /^For example/i,
    /^Consider this/i,
    /^Think about it/i,
    /^You should/i,
    /^You need to/i,
    /^You have to/i,
    /^You must/i,
    /^The best approach is/i,
    /^The recommended way is/i,
    /^I recommend/i,
    /^I suggest/i,
    /^I would suggest/i,
    /^It's important to/i,
    /^Make sure to/i,
    /^Remember to/i,
    /^Don't forget to/i,
    /^Always/i,
    /^Never/i,
    /^Usually/i,
    /^Typically/i,
    /^Generally/i,
    /^In most cases/i,
    /^In general/i,
    /^As a rule/i,
    /^As a general rule/i
  ]

  // Check for first-person statements that indicate user content
  const userIndicators = [
    /^I am/i,
    /^My name is/i,
    /^I work as/i,
    /^I like/i,
    /^I prefer/i,
    /^My favorite/i,
    /^I have/i,
    /^I want/i,
    /^I need/i,
    /^I'm/i,
    /^I was/i,
    /^I will/i,
    /^I would/i,
    /^I could/i,
    /^I should/i,
    /^I might/i,
    /^I may/i,
    /^I can/i,
    /^I do/i,
    /^I did/i,
    /^I have been/i,
    /^I had/i,
    /^I went/i,
    /^I came/i,
    /^I saw/i,
    /^I heard/i,
    /^I read/i,
    /^I wrote/i,
    /^I created/i,
    /^I built/i,
    /^I made/i,
    /^I started/i,
    /^I finished/i,
    /^I learned/i,
    /^I studied/i,
    /^I graduated/i,
    /^I worked/i,
    /^I lived/i,
    /^I moved/i,
    /^I bought/i,
    /^I sold/i,
    /^I owned/i,
    /^I founded/i,
    /^I started/i,
    /^I created/i,
    /^I built/i,
    /^I developed/i,
    /^I designed/i,
    /^I managed/i,
    /^I led/i,
    /^I supervised/i,
    /^I taught/i,
    /^I trained/i,
    /^I helped/i,
    /^I assisted/i,
    /^I supported/i,
    /^I worked on/i,
    /^I focused on/i,
    /^I specialized in/i,
    /^I'm good at/i,
    /^I'm bad at/i,
    /^I'm interested in/i,
    /^I'm passionate about/i,
    /^I care about/i,
    /^I believe in/i,
    /^I think/i,
    /^I feel/i,
    /^I hope/i,
    /^I dream/i,
    /^I plan to/i,
    /^I want to/i,
    /^I need to/i,
    /^I have to/i,
    /^I must/i,
    /^I should/i,
    /^I would like to/i,
    /^I would love to/i,
    /^I would prefer to/i,
    /^I would rather/i,
    /^I enjoy/i,
    /^I love/i,
    /^I hate/i,
    /^I dislike/i,
    /^I don't like/i,
    /^I can't stand/i,
    /^I'm allergic to/i,
    /^I'm afraid of/i,
    /^I'm scared of/i,
    /^I'm worried about/i,
    /^I'm concerned about/i,
    /^I'm excited about/i,
    /^I'm looking forward to/i,
    /^I'm planning to/i,
    /^I'm thinking about/i,
    /^I'm considering/i,
    /^I'm debating/i,
    /^I'm trying to/i,
    /^I'm working on/i,
    /^I'm studying/i,
    /^I'm learning/i,
    /^I'm practicing/i,
    /^I'm improving/i,
    /^I'm getting better at/i,
    /^I'm getting worse at/i,
    /^I'm getting older/i,
    /^I'm getting younger/i,
    /^I'm getting married/i,
    /^I'm getting divorced/i,
    /^I'm having a baby/i,
    /^I'm expecting/i,
    /^I'm pregnant/i,
    /^I'm sick/i,
    /^I'm healthy/i,
    /^I'm tired/i,
    /^I'm exhausted/i,
    /^I'm energized/i,
    /^I'm motivated/i,
    /^I'm inspired/i,
    /^I'm frustrated/i,
    /^I'm angry/i,
    /^I'm happy/i,
    /^I'm sad/i,
    /^I'm depressed/i,
    /^I'm anxious/i,
    /^I'm stressed/i,
    /^I'm relaxed/i,
    /^I'm calm/i,
    /^I'm nervous/i,
    /^I'm confident/i,
    /^I'm insecure/i,
    /^I'm proud/i,
    /^I'm ashamed/i,
    /^I'm embarrassed/i,
    /^I'm grateful/i,
    /^I'm thankful/i,
    /^I'm blessed/i,
    /^I'm lucky/i,
    /^I'm unlucky/i,
    /^I'm fortunate/i,
    /^I'm unfortunate/i,
    /^I'm successful/i,
    /^I'm failing/i,
    /^I'm struggling/i,
    /^I'm thriving/i,
    /^I'm growing/i,
    /^I'm changing/i,
    /^I'm evolving/i,
    /^I'm developing/i,
    /^I'm improving/i,
    /^I'm getting worse/i,
    /^I'm getting better/i,
    /^I'm getting stronger/i,
    /^I'm getting weaker/i,
    /^I'm getting smarter/i,
    /^I'm getting dumber/i,
    /^I'm getting wiser/i,
    /^I'm getting more experienced/i,
    /^I'm getting more skilled/i,
    /^I'm getting more knowledgeable/i,
    /^I'm getting more confident/i,
    /^I'm getting more comfortable/i,
    /^I'm getting more familiar/i,
    /^I'm getting more used to/i,
    /^I'm getting more accustomed to/i,
    /^I'm getting more adapted to/i,
    /^I'm getting more adjusted to/i,
    /^I'm getting more settled/i,
    /^I'm getting more established/i,
    /^I'm getting more organized/i,
    /^I'm getting more structured/i,
    /^I'm getting more systematic/i,
    /^I'm getting more methodical/i,
    /^I'm getting more disciplined/i,
    /^I'm getting more focused/i,
    /^I'm getting more determined/i,
    /^I'm getting more motivated/i,
    /^I'm getting more inspired/i,
    /^I'm getting more creative/i,
    /^I'm getting more innovative/i,
    /^I'm getting more original/i,
    /^I'm getting more unique/i,
    /^I'm getting more special/i,
    /^I'm getting more important/i,
    /^I'm getting more valuable/i,
    /^I'm getting more precious/i,
    /^I'm getting more rare/i,
    /^I'm getting more common/i,
    /^I'm getting more popular/i,
    /^I'm getting more famous/i,
    /^I'm getting more well-known/i,
    /^I'm getting more recognized/i,
    /^I'm getting more respected/i,
    /^I'm getting more admired/i,
    /^I'm getting more appreciated/i,
    /^I'm getting more loved/i,
    /^I'm getting more hated/i,
    /^I'm getting more disliked/i,
    /^I'm getting more ignored/i,
    /^I'm getting more forgotten/i,
    /^I'm getting more remembered/i,
    /^I'm getting more missed/i,
    /^I'm getting more wanted/i,
    /^I'm getting more needed/i,
    /^I'm getting more required/i,
    /^I'm getting more necessary/i,
    /^I'm getting more essential/i,
    /^I'm getting more critical/i,
    /^I'm getting more crucial/i,
    /^I'm getting more vital/i,
    /^I'm getting more important/i,
    /^I'm getting more significant/i,
    /^I'm getting more meaningful/i,
    /^I'm getting more purposeful/i,
    /^I'm getting more intentional/i,
    /^I'm getting more deliberate/i,
    /^I'm getting more conscious/i,
    /^I'm getting more aware/i,
    /^I'm getting more mindful/i,
    /^I'm getting more present/i,
    /^I'm getting more focused/i,
    /^I'm getting more concentrated/i,
    /^I'm getting more centered/i,
    /^I'm getting more balanced/i,
    /^I'm getting more stable/i,
    /^I'm getting more steady/i,
    /^I'm getting more consistent/i,
    /^I'm getting more reliable/i,
    /^I'm getting more dependable/i,
    /^I'm getting more trustworthy/i,
    /^I'm getting more honest/i,
    /^I'm getting more truthful/i,
    /^I'm getting more authentic/i,
    /^I'm getting more genuine/i,
    /^I'm getting more real/i,
    /^I'm getting more true/i,
    /^I'm getting more accurate/i,
    /^I'm getting more precise/i,
    /^I'm getting more exact/i,
    /^I'm getting more specific/i,
    /^I'm getting more detailed/i,
    /^I'm getting more thorough/i,
    /^I'm getting more comprehensive/i,
    /^I'm getting more complete/i,
    /^I'm getting more finished/i,
    /^I'm getting more done/i,
    /^I'm getting more accomplished/i,
    /^I'm getting more achieved/i,
    /^I'm getting more reached/i,
    /^I'm getting more attained/i,
    /^I'm getting more obtained/i,
    /^I'm getting more acquired/i,
    /^I'm getting more gained/i,
    /^I'm getting more earned/i,
    /^I'm getting more won/i,
    /^I'm getting more received/i,
    /^I'm getting more accepted/i,
    /^I'm getting more approved/i,
    /^I'm getting more confirmed/i,
    /^I'm getting more validated/i,
    /^I'm getting more verified/i,
    /^I'm getting more certified/i,
    /^I'm getting more licensed/i,
    /^I'm getting more qualified/i,
    /^I'm getting more trained/i,
    /^I'm getting more educated/i,
    /^I'm getting more informed/i,
    /^I'm getting more knowledgeable/i,
    /^I'm getting more experienced/i,
    /^I'm getting more skilled/i,
    /^I'm getting more talented/i,
    /^I'm getting more gifted/i,
    /^I'm getting more blessed/i,
    /^I'm getting more fortunate/i,
    /^I'm getting more lucky/i,
    /^I'm getting more successful/i,
    /^I'm getting more prosperous/i,
    /^I'm getting more wealthy/i,
    /^I'm getting more rich/i,
    /^I'm getting more poor/i,
    /^I'm getting more broke/i,
    /^I'm getting more bankrupt/i,
    /^I'm getting more indebted/i,
    /^I'm getting more in debt/i,
    /^I'm getting more financially stable/i,
    /^I'm getting more financially secure/i,
    /^I'm getting more financially independent/i,
    /^I'm getting more financially free/i,
    /^I'm getting more financially comfortable/i,
    /^I'm getting more financially well-off/i,
    /^I'm getting more financially successful/i,
    /^I'm getting more financially prosperous/i,
    /^I'm getting more financially wealthy/i,
    /^I'm getting more financially rich/i,
    /^I'm getting more financially poor/i,
    /^I'm getting more financially broke/i,
    /^I'm getting more financially bankrupt/i,
    /^I'm getting more financially indebted/i,
    /^I'm getting more financially in debt/i,
    /^I'm getting more financially unstable/i,
    /^I'm getting more financially insecure/i,
    /^I'm getting more financially dependent/i,
    /^I'm getting more financially trapped/i,
    /^I'm getting more financially uncomfortable/i,
    /^I'm getting more financially struggling/i,
    /^I'm getting more financially failing/i,
    /^I'm getting more financially unsuccessful/i,
    /^I'm getting more financially unprosperous/i,
    /^I'm getting more financially unwealthy/i,
    /^I'm getting more financially unrich/i,
    /^I'm getting more financially unpoor/i,
    /^I'm getting more financially unbroke/i,
    /^I'm getting more financially unbankrupt/i,
    /^I'm getting more financially unindebted/i,
    /^I'm getting more financially not in debt/i,
    /^I'm getting more financially stable/i,
    /^I'm getting more financially secure/i,
    /^I'm getting more financially independent/i,
    /^I'm getting more financially free/i,
    /^I'm getting more financially comfortable/i,
    /^I'm getting more financially well-off/i,
    /^I'm getting more financially successful/i,
    /^I'm getting more financially prosperous/i,
    /^I'm getting more financially wealthy/i,
    /^I'm getting more financially rich/i,
    /^I'm getting more financially poor/i,
    /^I'm getting more financially broke/i,
    /^I'm getting more financially bankrupt/i,
    /^I'm getting more financially indebted/i,
    /^I'm getting more financially in debt/i,
    /^I'm getting more financially unstable/i,
    /^I'm getting more financially insecure/i,
    /^I'm getting more financially dependent/i,
    /^I'm getting more financially trapped/i,
    /^I'm getting more financially uncomfortable/i,
    /^I'm getting more financially struggling/i,
    /^I'm getting more financially failing/i,
    /^I'm getting more financially unsuccessful/i,
    /^I'm getting more financially unprosperous/i,
    /^I'm getting more financially unwealthy/i,
    /^I'm getting more financially unrich/i,
    /^I'm getting more financially unpoor/i,
    /^I'm getting more financially unbroke/i,
    /^I'm getting more financially unbankrupt/i,
    /^I'm getting more financially unindebted/i,
    /^I'm getting more financially not in debt/i
  ]

  const hasAIResponse = aiIndicators.some(pattern =>
    pattern.test(trimmedContent)
  )
  const hasUserContent = userIndicators.some(pattern =>
    pattern.test(trimmedContent)
  )

  // Apply validation based on level
  switch (validationLevel) {
    case "strict":
      // Strict: Must have user content and no AI response indicators
      if (hasAIResponse) {
        console.warn(
          "❌ [STRICT] Rejected potential AI response as memory:",
          trimmedContent.substring(0, 50)
        )
        return false
      }
      if (!hasUserContent) {
        console.warn(
          "❌ [STRICT] Rejected content without clear user indicators:",
          trimmedContent.substring(0, 50)
        )
        return false
      }
      break

    case "normal":
      // Normal: Reject if it looks like an AI response and doesn't have clear user content
      if (hasAIResponse && !hasUserContent) {
        console.warn(
          "❌ [NORMAL] Rejected potential AI response as memory:",
          trimmedContent.substring(0, 50)
        )
        return false
      }
      break

    case "lenient":
      // Lenient: Only reject obvious AI responses
      if (hasAIResponse && !hasUserContent && trimmedContent.length > 20) {
        console.warn(
          "❌ [LENIENT] Rejected obvious AI response as memory:",
          trimmedContent.substring(0, 50)
        )
        return false
      }
      break
  }

  return true
}

/**
 * Checks if content appears to be an AI response
 * @param content The content to check
 * @returns true if content looks like an AI response
 */
export const isAIResponse = (content: string): boolean => {
  if (!content || typeof content !== "string") return false

  const aiPatterns = [
    /^I can help you/i,
    /^Here's how/i,
    /^Let me explain/i,
    /^Based on/i,
    /^I understand/i,
    /^That's a great question/i,
    /^I'll help you/i,
    /^Here's what/i,
    /^To answer your question/i,
    /^I'd be happy to/i,
    /^As an AI assistant/i,
    /^I'm here to help/i,
    /^Let me assist you/i,
    /^I can assist you/i,
    /^Here's the answer/i,
    /^The answer is/i,
    /^To solve this/i,
    /^Here's a solution/i,
    /^The solution is/i,
    /^You can solve this by/i,
    /^To fix this issue/i,
    /^The problem is/i,
    /^The issue is/i,
    /^Let me show you/i,
    /^I'll show you/i,
    /^Here's an example/i,
    /^For example/i,
    /^Consider this/i,
    /^Think about it/i,
    /^You should/i,
    /^You need to/i,
    /^You have to/i,
    /^You must/i,
    /^The best approach is/i,
    /^The recommended way is/i,
    /^I recommend/i,
    /^I suggest/i,
    /^I would suggest/i,
    /^It's important to/i,
    /^Make sure to/i,
    /^Remember to/i,
    /^Don't forget to/i,
    /^Always/i,
    /^Never/i,
    /^Usually/i,
    /^Typically/i,
    /^Generally/i,
    /^In most cases/i,
    /^In general/i,
    /^As a rule/i,
    /^As a general rule/i
  ]

  return aiPatterns.some(pattern => pattern.test(content.trim()))
}

/**
 * Checks if content contains user information
 * @param content The content to check
 * @returns true if content contains user information
 */
export const hasUserContent = (content: string): boolean => {
  if (!content || typeof content !== "string") return false

  const userPatterns = [
    /^I am/i,
    /^My name is/i,
    /^I work as/i,
    /^I like/i,
    /^I prefer/i,
    /^My favorite/i,
    /^I have/i,
    /^I want/i,
    /^I need/i,
    /^I'm/i,
    /^I was/i,
    /^I will/i,
    /^I would/i,
    /^I could/i,
    /^I should/i,
    /^I might/i,
    /^I may/i,
    /^I can/i,
    /^I do/i,
    /^I did/i,
    /^I have been/i,
    /^I had/i,
    /^I went/i,
    /^I came/i,
    /^I saw/i,
    /^I heard/i,
    /^I read/i,
    /^I wrote/i,
    /^I created/i,
    /^I built/i,
    /^I made/i,
    /^I started/i,
    /^I finished/i,
    /^I learned/i,
    /^I studied/i,
    /^I graduated/i,
    /^I worked/i,
    /^I lived/i,
    /^I moved/i,
    /^I bought/i,
    /^I sold/i,
    /^I owned/i,
    /^I founded/i,
    /^I started/i,
    /^I created/i,
    /^I built/i,
    /^I developed/i,
    /^I designed/i,
    /^I managed/i,
    /^I led/i,
    /^I supervised/i,
    /^I taught/i,
    /^I trained/i,
    /^I helped/i,
    /^I assisted/i,
    /^I supported/i,
    /^I worked on/i,
    /^I focused on/i,
    /^I specialized in/i,
    /^I'm good at/i,
    /^I'm bad at/i,
    /^I'm interested in/i,
    /^I'm passionate about/i,
    /^I care about/i,
    /^I believe in/i,
    /^I think/i,
    /^I feel/i,
    /^I hope/i,
    /^I dream/i,
    /^I plan to/i,
    /^I want to/i,
    /^I need to/i,
    /^I have to/i,
    /^I must/i,
    /^I should/i,
    /^I would like to/i,
    /^I would love to/i,
    /^I would prefer to/i,
    /^I would rather/i,
    /^I enjoy/i,
    /^I love/i,
    /^I hate/i,
    /^I dislike/i,
    /^I don't like/i,
    /^I can't stand/i,
    /^I'm allergic to/i,
    /^I'm afraid of/i,
    /^I'm scared of/i,
    /^I'm worried about/i,
    /^I'm concerned about/i,
    /^I'm excited about/i,
    /^I'm looking forward to/i,
    /^I'm planning to/i,
    /^I'm thinking about/i,
    /^I'm considering/i,
    /^I'm debating/i,
    /^I'm trying to/i,
    /^I'm working on/i,
    /^I'm studying/i,
    /^I'm learning/i,
    /^I'm practicing/i,
    /^I'm improving/i,
    /^I'm getting better at/i,
    /^I'm getting worse at/i,
    /^I'm getting older/i,
    /^I'm getting younger/i,
    /^I'm getting married/i,
    /^I'm getting divorced/i,
    /^I'm having a baby/i,
    /^I'm expecting/i,
    /^I'm pregnant/i,
    /^I'm sick/i,
    /^I'm healthy/i,
    /^I'm tired/i,
    /^I'm exhausted/i,
    /^I'm energized/i,
    /^I'm motivated/i,
    /^I'm inspired/i,
    /^I'm frustrated/i,
    /^I'm angry/i,
    /^I'm happy/i,
    /^I'm sad/i,
    /^I'm depressed/i,
    /^I'm anxious/i,
    /^I'm stressed/i,
    /^I'm relaxed/i,
    /^I'm calm/i,
    /^I'm nervous/i,
    /^I'm confident/i,
    /^I'm insecure/i,
    /^I'm proud/i,
    /^I'm ashamed/i,
    /^I'm embarrassed/i,
    /^I'm grateful/i,
    /^I'm thankful/i,
    /^I'm blessed/i,
    /^I'm lucky/i,
    /^I'm unlucky/i,
    /^I'm fortunate/i,
    /^I'm unfortunate/i,
    /^I'm successful/i,
    /^I'm failing/i,
    /^I'm struggling/i,
    /^I'm thriving/i,
    /^I'm growing/i,
    /^I'm changing/i,
    /^I'm evolving/i,
    /^I'm developing/i,
    /^I'm improving/i,
    /^I'm getting worse/i,
    /^I'm getting better/i,
    /^I'm getting stronger/i,
    /^I'm getting weaker/i,
    /^I'm getting smarter/i,
    /^I'm getting dumber/i,
    /^I'm getting wiser/i,
    /^I'm getting more experienced/i,
    /^I'm getting more skilled/i,
    /^I'm getting more knowledgeable/i,
    /^I'm getting more confident/i,
    /^I'm getting more comfortable/i,
    /^I'm getting more familiar/i,
    /^I'm getting more used to/i,
    /^I'm getting more accustomed to/i,
    /^I'm getting more adapted to/i,
    /^I'm getting more adjusted to/i,
    /^I'm getting more settled/i,
    /^I'm getting more established/i,
    /^I'm getting more organized/i,
    /^I'm getting more structured/i,
    /^I'm getting more systematic/i,
    /^I'm getting more methodical/i,
    /^I'm getting more disciplined/i,
    /^I'm getting more focused/i,
    /^I'm getting more determined/i,
    /^I'm getting more motivated/i,
    /^I'm getting more inspired/i,
    /^I'm getting more creative/i,
    /^I'm getting more innovative/i,
    /^I'm getting more original/i,
    /^I'm getting more unique/i,
    /^I'm getting more special/i,
    /^I'm getting more important/i,
    /^I'm getting more valuable/i,
    /^I'm getting more precious/i,
    /^I'm getting more rare/i,
    /^I'm getting more common/i,
    /^I'm getting more popular/i,
    /^I'm getting more famous/i,
    /^I'm getting more well-known/i,
    /^I'm getting more recognized/i,
    /^I'm getting more respected/i,
    /^I'm getting more admired/i,
    /^I'm getting more appreciated/i,
    /^I'm getting more loved/i,
    /^I'm getting more hated/i,
    /^I'm getting more disliked/i,
    /^I'm getting more ignored/i,
    /^I'm getting more forgotten/i,
    /^I'm getting more remembered/i,
    /^I'm getting more missed/i,
    /^I'm getting more wanted/i,
    /^I'm getting more needed/i,
    /^I'm getting more required/i,
    /^I'm getting more necessary/i,
    /^I'm getting more essential/i,
    /^I'm getting more critical/i,
    /^I'm getting more crucial/i,
    /^I'm getting more vital/i,
    /^I'm getting more important/i,
    /^I'm getting more significant/i,
    /^I'm getting more meaningful/i,
    /^I'm getting more purposeful/i,
    /^I'm getting more intentional/i,
    /^I'm getting more deliberate/i,
    /^I'm getting more conscious/i,
    /^I'm getting more aware/i,
    /^I'm getting more mindful/i,
    /^I'm getting more present/i,
    /^I'm getting more focused/i,
    /^I'm getting more concentrated/i,
    /^I'm getting more centered/i,
    /^I'm getting more balanced/i,
    /^I'm getting more stable/i,
    /^I'm getting more steady/i,
    /^I'm getting more consistent/i,
    /^I'm getting more reliable/i,
    /^I'm getting more dependable/i,
    /^I'm getting more trustworthy/i,
    /^I'm getting more honest/i,
    /^I'm getting more truthful/i,
    /^I'm getting more authentic/i,
    /^I'm getting more genuine/i,
    /^I'm getting more real/i,
    /^I'm getting more true/i,
    /^I'm getting more accurate/i,
    /^I'm getting more precise/i,
    /^I'm getting more exact/i,
    /^I'm getting more specific/i,
    /^I'm getting more detailed/i,
    /^I'm getting more thorough/i,
    /^I'm getting more comprehensive/i,
    /^I'm getting more complete/i,
    /^I'm getting more finished/i,
    /^I'm getting more done/i,
    /^I'm getting more accomplished/i,
    /^I'm getting more achieved/i,
    /^I'm getting more reached/i,
    /^I'm getting more attained/i,
    /^I'm getting more obtained/i,
    /^I'm getting more acquired/i,
    /^I'm getting more gained/i,
    /^I'm getting more earned/i,
    /^I'm getting more won/i,
    /^I'm getting more received/i,
    /^I'm getting more accepted/i,
    /^I'm getting more approved/i,
    /^I'm getting more confirmed/i,
    /^I'm getting more validated/i,
    /^I'm getting more verified/i,
    /^I'm getting more certified/i,
    /^I'm getting more licensed/i,
    /^I'm getting more qualified/i,
    /^I'm getting more trained/i,
    /^I'm getting more educated/i,
    /^I'm getting more informed/i,
    /^I'm getting more knowledgeable/i,
    /^I'm getting more experienced/i,
    /^I'm getting more skilled/i,
    /^I'm getting more talented/i,
    /^I'm getting more gifted/i,
    /^I'm getting more blessed/i,
    /^I'm getting more fortunate/i,
    /^I'm getting more lucky/i,
    /^I'm getting more successful/i,
    /^I'm getting more prosperous/i,
    /^I'm getting more wealthy/i,
    /^I'm getting more rich/i,
    /^I'm getting more poor/i,
    /^I'm getting more broke/i,
    /^I'm getting more bankrupt/i,
    /^I'm getting more indebted/i,
    /^I'm getting more in debt/i,
    /^I'm getting more financially stable/i,
    /^I'm getting more financially secure/i,
    /^I'm getting more financially independent/i,
    /^I'm getting more financially free/i,
    /^I'm getting more financially comfortable/i,
    /^I'm getting more financially well-off/i,
    /^I'm getting more financially successful/i,
    /^I'm getting more financially prosperous/i,
    /^I'm getting more financially wealthy/i,
    /^I'm getting more financially rich/i,
    /^I'm getting more financially poor/i,
    /^I'm getting more financially broke/i,
    /^I'm getting more financially bankrupt/i,
    /^I'm getting more financially indebted/i,
    /^I'm getting more financially in debt/i,
    /^I'm getting more financially unstable/i,
    /^I'm getting more financially insecure/i,
    /^I'm getting more financially dependent/i,
    /^I'm getting more financially trapped/i,
    /^I'm getting more financially uncomfortable/i,
    /^I'm getting more financially struggling/i,
    /^I'm getting more financially failing/i,
    /^I'm getting more financially unsuccessful/i,
    /^I'm getting more financially unprosperous/i,
    /^I'm getting more financially unwealthy/i,
    /^I'm getting more financially unrich/i,
    /^I'm getting more financially unpoor/i,
    /^I'm getting more financially unbroke/i,
    /^I'm getting more financially unbankrupt/i,
    /^I'm getting more financially unindebted/i,
    /^I'm getting more financially not in debt/i,
    /^I'm getting more financially stable/i,
    /^I'm getting more financially secure/i,
    /^I'm getting more financially independent/i,
    /^I'm getting more financially free/i,
    /^I'm getting more financially comfortable/i,
    /^I'm getting more financially well-off/i,
    /^I'm getting more financially successful/i,
    /^I'm getting more financially prosperous/i,
    /^I'm getting more financially wealthy/i,
    /^I'm getting more financially rich/i,
    /^I'm getting more financially poor/i,
    /^I'm getting more financially broke/i,
    /^I'm getting more financially bankrupt/i,
    /^I'm getting more financially indebted/i,
    /^I'm getting more financially in debt/i,
    /^I'm getting more financially unstable/i,
    /^I'm getting more financially insecure/i,
    /^I'm getting more financially dependent/i,
    /^I'm getting more financially trapped/i,
    /^I'm getting more financially uncomfortable/i,
    /^I'm getting more financially struggling/i,
    /^I'm getting more financially failing/i,
    /^I'm getting more financially unsuccessful/i,
    /^I'm getting more financially unprosperous/i,
    /^I'm getting more financially unwealthy/i,
    /^I'm getting more financially unrich/i,
    /^I'm getting more financially unpoor/i,
    /^I'm getting more financially unbroke/i,
    /^I'm getting more financially unbankrupt/i,
    /^I'm getting more financially unindebted/i,
    /^I'm getting more financially not in debt/i
  ]

  return userPatterns.some(pattern => pattern.test(content.trim()))
}
